## Hierarchical Clustering

In [2]:
###############################################################################
# Perform clustering the identified SVGs from the CKD Kidney Xenium Samples
###############################################################################
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster import hierarchy
import h5py
import scanpy as sc
import os

In [ ]:
# Set up directory calls and samples
data_path = "________" # enter your data path here
dir_folder = "data/XeniumDKD/XeniumDKD/"
sample_1 = "40440"
sample_2 = "40610"
sample_3 = "40775"
sample_4 = "5582"

In [4]:
######################################################################
# CKD sig - load in meta-p values
######################################################################
df1 = pd.read_csv(os.path.join(data_path, dir_folder, "CKD_P_values_meta.csv"),header=0)
df1
df1 = df1[df1["meta_p"] < 0.05]
genelist_1= df1.index.tolist()
print(len(genelist_1))
unique = genelist_1
print(unique)

75
['ACTA2', 'ANPEP', 'APOE', 'AQP1', 'AQP2', 'AQP3', 'ATF4', 'ATP6V1B1', 'B2M', 'BBOX1', 'C1R', 'C3', 'CALB1', 'CCNI', 'CDH16', 'CDH6', 'COL1A1', 'COL4A1', 'COL4A2', 'CRYAB', 'CXCL12', 'DDX5', 'DPP4', 'EMCN', 'EPCAM', 'F13A1', 'FHL2', 'FLNA', 'FLT1', 'FN1', 'FTH1', 'GATA3', 'GATM', 'GSTA3', 'HIF1A', 'HSD11B2', 'IGFBP5', 'IGKC', 'IL7R', 'ITGAV', 'ITGB1', 'ITGB8', 'JCHAIN', 'LRP2', 'LUM', 'MMP7', 'NES', 'NPHS2', 'PDK4', 'PODXL', 'POSTN', 'PPARGC1A', 'PROM1', 'PTPRC', 'SCNN1G', 'SDC4', 'SERPINA1', 'SLC12A1', 'SLC12A3', 'SLC22A8', 'SLC5A12', 'SLC8A1', 'SLPI', 'SON', 'SPP1', 'STAT3', 'TACSTD2', 'TAGLN', 'THY1', 'TIMP1', 'TMSB4X', 'TPM1', 'UMOD', 'VCAM1', 'VIM']

In [5]:
# Writing out the significant SVGs for later analysis
with open(os.path.join(data_path, dir_folder,'CKD_allsig.txt'), 'w') as f:
    f.write('\n'.join(unique))

In [ ]:
######################################################################
# CKD 1 - 40440
######################################################################
expFilename_1 = os.path.join(data_path, dir_folder,sample_1,"count.csv")
coordFilename_1 = os.path.join(data_path, dir_folder,sample_1,"spa.csv")
df = pd.read_csv(expFilename_1)

df_svg_1 = df[[c for c in df.columns if c in unique]]
df_svg_1 = df_svg_1.T
df_svg_1 = df_svg_1.transform(lambda x: np.log(x+1))

## Plot hierarchical linkage
clusters = hierarchy.linkage(df_svg_1, method="ward")
plt.figure(figsize=(20, 6))
dendrogram = hierarchy.dendrogram(clusters, labels=df_svg_1.index, leaf_font_size=4)
plt.savefig(os.path.join(data_path, dir_folder,sample_1,'kidneysvg_sig_40440.png'),dpi=600)
plt.close()

In [ ]:
######################################################################
# CKD 2 - 40610
######################################################################
expFilename_2 = os.path.join(data_path, dir_folder,sample_2,"count.csv")
coordFilename_2 = os.path.join(data_path, dir_folder,sample_2,"spa.csv")
df = pd.read_csv(expFilename_2)

df_svg_2 = df[[c for c in df.columns if c in unique]]
df_svg_2 = df_svg_2.T
df_svg_2 = df_svg_2.transform(lambda x: np.log(x+1))

## Plot hierarchical linkage
clusters = hierarchy.linkage(df_svg_2, method="ward")
plt.figure(figsize=(20, 6))
dendrogram = hierarchy.dendrogram(clusters, labels=df_svg_2.index, leaf_font_size=4)
plt.savefig(os.path.join(data_path, dir_folder,sample_2,'kidneysvg_sig_40610.png'),dpi=600)
plt.close()

In [ ]:
######################################################################
# CKD 3 - 40775
######################################################################
expFilename_3 = os.path.join(data_path, dir_folder,sample_3,"count.csv")
coordFilename_3 = os.path.join(data_path, dir_folder,sample_3,"spa.csv")
df = pd.read_csv(expFilename_3)

df_svg_3 = df[[c for c in df.columns if c in unique]]
df_svg_3 = df_svg_3.T
df_svg_3 = df_svg_3.transform(lambda x: np.log(x+1))

## Plot hierarchical linkage
clusters = hierarchy.linkage(df_svg_3, method="ward")
plt.figure(figsize=(20, 6))
dendrogram = hierarchy.dendrogram(clusters, labels=df_svg_3.index, leaf_font_size=4)
plt.savefig(os.path.join(data_path, dir_folder,sample_3,'kidneysvg_sig_40775.png'),dpi=600)
plt.close()

In [ ]:
######################################################################
# CKD 4 - 5582
######################################################################
expFilename_4 = os.path.join(data_path, dir_folder,sample_4,"count.csv")
coordFilename_4 = os.path.join(data_path, dir_folder,sample_4,"spa.csv")
df = pd.read_csv(expFilename_4)

df_svg_4 = df[[c for c in df.columns if c in unique]]
df_svg_4 = df_svg_4.T
df_svg_4 = df_svg_4.transform(lambda x: np.log(x+1))

## Plot hierarchical linkage
clusters = hierarchy.linkage(df_svg_4, method="ward")
plt.figure(figsize=(20, 6))
dendrogram = hierarchy.dendrogram(clusters, labels=df_svg_4.index, leaf_font_size=4)
plt.savefig(os.path.join(data_path, dir_folder,sample_4,'kidneysvg_sig_5582.png'),dpi=600)
plt.close()

In [10]:
# Size of each sample
print(df_svg_1.shape)
print(df_svg_2.shape)
print(df_svg_3.shape)
print(df_svg_4.shape)

(75, 30865)
(75, 92438)
(75, 50394)
(75, 35352)

In [11]:
# Combining all cells from samples to cluster all cells
CKD_sample_svg = pd.concat([df_svg_1, df_svg_2, df_svg_3, df_svg_4], axis = 1)
CKD_sample_svg.shape

(75, 209049)

In [ ]:
## Plotting all samples' cells linkage
clusters = hierarchy.linkage(CKD_sample_svg, method="ward")
plt.figure(figsize=(20, 6))
dendrogram = hierarchy.dendrogram(clusters, labels=CKD_sample_svg.index, leaf_font_size=4)
plt.savefig(os.path.join(data_path, dir_folder,'CKDAll_kidneysvg_sig.png'),dpi=600)
plt.close()

In [13]:
# Since there are three groups in the hierarchical tree, we print out the genes belonging to each cluster
clustering_model = AgglomerativeClustering(n_clusters=3, linkage="ward")
# clustering_model = AgglomerativeClustering(n_clusters=4, linkage="ward")
clustering_model.fit(CKD_sample_svg)
labels = clustering_model.labels_

glist = CKD_sample_svg.iloc[labels==0].index.tolist()

with open(os.path.join(data_path, dir_folder,'kidney_0_genes_sig.txt'), 'w') as f:
    f.write('\n'.join(glist))

glist = CKD_sample_svg.iloc[labels==1].index.tolist()

with open(os.path.join(data_path, dir_folder,'kidney_1_genes_sig.txt'), 'w') as f:
    f.write('\n'.join(glist))

glist = CKD_sample_svg.iloc[labels==2].index.tolist()

with open(os.path.join(data_path, dir_folder,'kidney_2_genes_sig.txt'), 'w') as f:
    f.write('\n'.join(glist))

In [14]:
######################################################################
# Here, we can plot the individual gene expression for each gene
# plotting for: 40440
######################################################################

coord=pd.read_csv(coordFilename_1)
t1= pd.read_csv(expFilename_1,index_col=0)
sample="40440"

## Debug info
print("Loading ready.")

def visualGene(geneName):    
    exp = t1[geneName].tolist()
    # exp = exp/np.max(exp)
    df1 = pd.DataFrame({'x': coord['x'],
                    'y': coord['y'],
                    'z': exp})
    plt.autoscale()
    plt.scatter(df1.x, df1.y, c=df1.z, cmap='YlGn', s=10)
    plt.colorbar()
    plt.show()

def saveGenePlotLog(geneName):    
    exp = t1[geneName].tolist()
    expo = []
    for elem in exp:
        expo.append(np.log(float(elem+1)))
    df1 = pd.DataFrame({'x': coord['x'],
                    'y': coord['y'],
                    'z': expo})
    plt.figure(dpi=300)
    plt.scatter(df1.x, df1.y, c=df1.z, cmap='YlGn', s=10)
    plt.colorbar()
    plt.savefig(os.path.join(data_path, dir_folder, "geneplots",sample, geneName+'.jpg'))
    plt.close()

Loading ready.

In [ ]:
with open(os.path.join(data_path, dir_folder,'kidney_0_genes_sig.txt')) as f:
    lines = f.readlines()
    for line in lines:
        line = line.strip()
        print(line)
        saveGenePlotLog(line)

In [16]:
with open(os.path.join(data_path, dir_folder,'kidney_1_genes_sig.txt')) as f:
    lines = f.readlines()
    for line in lines:
        line = line.strip()
        print(line)
        saveGenePlotLog(line)

FTH1
VIM
TMSB4X
DDX5
B2M

In [ ]:
with open(os.path.join(data_path, dir_folder,'kidney_2_genes_sig.txt')) as f:
    lines = f.readlines()
    for line in lines:
        line = line.strip()
        print(line)
        saveGenePlotLog(line)

## Pathway Expression

In [ ]:
# Subset only significant genes for pathway expression
######################################################################
# CKD sig
######################################################################
df1 = pd.read_csv(os.path.join(data_path, dir_folder,"CKD_P_values_meta.csv"),header=0)
df1
df1 = df1[df1["meta_p"] < 0.05]
genelist_1= df1.index.tolist()
unique = genelist_1
print(unique)
len(unique)

['ACTA2', 'ANPEP', 'APOE', 'AQP1', 'AQP2', 'AQP3', 'ATF4', 'ATP6V1B1', 'B2M', 'BBOX1', 'C1R', 'C3', 'CALB1', 'CCNI', 'CDH16', 'CDH6', 'COL1A1', 'COL4A1', 'COL4A2', 'CRYAB', 'CXCL12', 'DDX5', 'DPP4', 'EMCN', 'EPCAM', 'F13A1', 'FHL2', 'FLNA', 'FLT1', 'FN1', 'FTH1', 'GATA3', 'GATM', 'GSTA3', 'HIF1A', 'HSD11B2', 'IGFBP5', 'IGKC', 'IL7R', 'ITGAV', 'ITGB1', 'ITGB8', 'JCHAIN', 'LRP2', 'LUM', 'MMP7', 'NES', 'NPHS2', 'PDK4', 'PODXL', 'POSTN', 'PPARGC1A', 'PROM1', 'PTPRC', 'SCNN1G', 'SDC4', 'SERPINA1', 'SLC12A1', 'SLC12A3', 'SLC22A8', 'SLC5A12', 'SLC8A1', 'SLPI', 'SON', 'SPP1', 'STAT3', 'TACSTD2', 'TAGLN', 'THY1', 'TIMP1', 'TMSB4X', 'TPM1', 'UMOD', 'VCAM1', 'VIM']

75

In [57]:
# Readin in pathway gene_lists
with open(os.path.join(data_path, dir_folder,"GO_0050900.txt"), 'r') as file:
    li = [line.strip()[0:].split() for line in file]

# Number of Genes in the pathway in the file
print(li[0])

['DPP4', 'FLT1', 'GATA3', 'ITGB1', 'CXCL12', 'THY1', 'UMOD', 'VCAM1']

In [58]:
# Read in counts
sample = "40440"
counts=sc.read_csv(os.path.join(data_path, dir_folder, sample, "count.csv"))

# Keeping only significant genes
counts = counts[:,unique]

In [59]:
counts.to_df().columns
counts.to_df()

,FTH1,SPP1,GATM,AQP1,IGKC,IGFBP5,CRYAB,VIM,TMSB4X,SLC8A1,...,FGF14,FOXP3,TP63,CD1A,CXCL3,CHAC1,MMP9,SLC26A3,ABCC11,TRPM6
aaaadphl-1,17.0,2.0,0.0,1.0,4.0,2.0,2.0,5.0,13.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
aaaanbkc-1,14.0,1.0,0.0,0.0,3.0,8.0,0.0,4.0,19.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
aaabgonc-1,11.0,3.0,0.0,1.0,2.0,0.0,0.0,1.0,11.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
aaafdnem-1,12.0,2.0,1.0,0.0,2.0,3.0,1.0,3.0,9.0,4.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
aaafkijh-1,22.0,7.0,0.0,1.0,1.0,3.0,1.0,6.0,10.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
oinoojgn-1,12.0,2.0,0.0,1.0,6.0,20.0,0.0,8.0,11.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
oioalono-1,7.0,5.0,0.0,0.0,3.0,0.0,0.0,1.0,6.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
oiocgehj-1,2.0,11.0,0.0,1.0,3.0,0.0,0.0,2.0,0.0,12.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
oioddcdb-1,9.0,0.0,0.0,0.0,14.0,1.0,0.0,12.0,15.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
oiognhbl-1,5.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
# Python function for intersection
def intersection(lst1, lst2):
    lst3 = [value for value in lst1 if value in lst2]
    return lst3
 
# Overlap between pathway genes and Sample genes
lst1 = li[0]
lst2 = list(counts.to_df().columns)
print(intersection(lst1, lst2))

['DPP4', 'FLT1', 'GATA3', 'ITGB1', 'CXCL12', 'THY1', 'UMOD', 'VCAM1']

In [61]:
# Finding pathway scores using gene lists and gene expression
data = []
for i in range(0, len(li)):
    if len(li[i]) >= 5:
        name = "P" + str(i)
        temp = sc.tl.score_genes(counts, li[i], score_name=name, copy=True)
        if 'P0' in temp.obs and i != 0:
            del temp.obs['P0']
        data.append(temp.obs)
counts.obs = pd.concat(data, axis=1)

In [62]:
counts.obs

                  P0
aaaadphl-1  1.000000
aaaanbkc-1 -0.062500
aaabgonc-1  0.843750
aaafdnem-1  0.343750
aaafkijh-1  1.171875
...              ...
oinoojgn-1  1.078125
oioalono-1 -0.218750
oiocgehj-1 -0.250000
oioddcdb-1 -0.187500
oiognhbl-1  0.078125

[30865 rows x 1 columns]

In [67]:
# Write out to file
counts.obs.to_csv(os.path.join(data_path, dir_folder, sample, "GO_0050900_pathwaycount.csv"))